setono_sylius_terms_admin_terms:
    resource: |
        alias: setono_sylius_terms.terms
        section: admin
        templates: "@SyliusAdmin\\shared\\crud"
        redirect: update
        grid: setono_sylius_terms_terms
    type: sylius.resource
