sylius_fixtures:
    suites:
        default:
            fixtures:

                # Adding some extra locales/currencies/channels
                # to show how terms working

                # Shipping/payment methods also required to be defined
                # for each additional channel

                locale:
                    options:
                        locales:
                            # - en_US # already there
                            - de_DE
                            - fr_FR
                            - uk_UA

                currency:
                    options:
                        currencies:
                            # - USD # already there
                            # - EUR # already there
                            - UAH

                channel:
                    options:
                        custom:
                            eu_web_store:
                                name: "EU Web Store"
                                code: EU_WEB
                                locales:
                                    - en_US
                                    - de_DE
                                    - fr_FR
                                currencies:
                                    - EUR
                                enabled: true
                                hostname: "localhost"
                            ua_web_store:
                                name: "UA Web Store"
                                code: UA_WEB
                                locales:
                                    - en_US
                                    - uk_UA
                                base_currency: USD
                                currencies:
                                    - USD
                                    - UAH
                                enabled: true
                                hostname: "localhost"

                payment_method:
                    options:
                        custom:
                            eu_bank_transfer:
                                code: eu_bank_transfer
                                name: "EU Bank transfer"
                                channels:
                                    - EU_WEB
                                    - UA_WEB
                                enabled: true

                shipping_method:
                    options:
                        custom:
                            eu_courier:
                                code: eu_courier
                                name: "EU courier"
                                enabled: true
                                channels:
                                    - EU_WEB
                                    - UA_WEB

                setono_terms:
                    options:
                        custom:
                            terms_eula_us:
                                code: eula_us
                                name: EULA for United States
                                slug: eula-us
                                label: Accept US EULA terms
                                channels:
                                  - FASHION_WEB
                            terms_eula_eu:
                                code: eula_eu
                                name: EULA for EU
                                slug: eula-eu
                                label: Accept [link:EU EULA terms]
                                translations:
                                    fr_FR:
                                        name: CLUF
                                        slug: cluf
                                channels:
                                  - EU_WEB
                            terms_terms_and_conditions:
                                code: terms_and_conditions
                                name: Terms and Conditions
                                slug: terms-conditions
                                label: Accept [link:Terms and conditions]
                                translations:
                                    fr_FR:
                                        name: Termes et conditions
                                        slug: termes-conditions
                                    de_DE:
                                        name: Geschäftsbedingungen
                                channels:
                                  - FASHION_WEB
                                  - EU_WEB
